In [1]:
import torch
import numpy as np

In [9]:
'''
Advanced indexing and masking
Conditional filtering with Boolean masking.
Create a random tensor T with 20 elements. Find and print all elements in T that are greater than 0.5, but less than 0.7 and have the digit 6 in them
'''
r = torch.rand((5,4))
mask = (r>0.5) & (r<0.7) 
greater = r[mask]
print(r)
print(mask)
print(greater)



tensor([[0.8301, 0.9302, 0.7488, 0.3411],
        [0.1528, 0.4557, 0.6848, 0.1411],
        [0.9044, 0.2544, 0.3947, 0.4413],
        [0.6384, 0.7066, 0.3714, 0.6816],
        [0.8234, 0.2010, 0.5748, 0.5019]])
tensor([[False, False, False, False],
        [False, False,  True, False],
        [False, False, False, False],
        [ True, False, False,  True],
        [False, False,  True,  True]])
tensor([0.6848, 0.6384, 0.6816, 0.5748, 0.5019])


In [8]:
'''
Using integer tensors for indexing (fancy indexing).
Create a random tensor data with shape (10, 10). Use a 1D tensor indices containing integers to select specific rows from data. Select rows at indices [0, 5, 9, 2].
'''
a = torch.rand((10,10))
b = [0,5,9,2]
indices = torch.tensor(b)
rand_indices = torch.randperm(10)
inte = a[indices]
ran = a[rand_indices]


In [9]:
print(a)
print(indices)
print(inte)
print(ran)

tensor([[0.1323, 0.7174, 0.6548, 0.2595, 0.4747, 0.5486, 0.9330, 0.6111, 0.3577,
         0.2788],
        [0.0151, 0.6175, 0.0587, 0.9890, 0.6444, 0.6035, 0.6090, 0.0676, 0.3168,
         0.3567],
        [0.1091, 0.8203, 0.2393, 0.3100, 0.5158, 0.1769, 0.6600, 0.4971, 0.2836,
         0.5723],
        [0.6451, 0.6073, 0.5451, 0.5359, 0.7672, 0.3021, 0.7387, 0.0016, 0.6932,
         0.7369],
        [0.9532, 0.4255, 0.4772, 0.6492, 0.2448, 0.5133, 0.7209, 0.7258, 0.3459,
         0.5275],
        [0.0669, 0.4131, 0.8702, 0.4299, 0.0503, 0.4635, 0.3048, 0.3566, 0.7250,
         0.0279],
        [0.9012, 0.0299, 0.0560, 0.1958, 0.9424, 0.4657, 0.4985, 0.0035, 0.1929,
         0.8814],
        [0.0955, 0.4804, 0.7118, 0.4707, 0.9299, 0.9293, 0.5118, 0.9068, 0.9761,
         0.4839],
        [0.5760, 0.0463, 0.9772, 0.5790, 0.1438, 0.9615, 0.6336, 0.5087, 0.2348,
         0.0188],
        [0.8460, 0.4445, 0.3313, 0.9334, 0.7865, 0.9567, 0.7141, 0.2914, 0.3827,
         0.9261]])
tensor([0

In [ ]:
'''
Conditional element replacement with torch.where.
Create a random tensor x of shape (5, 5). Use torch.where to create a new tensor where all values in x greater than 0.5 are replaced with 1, and all other values are replaced with 0.
'''
x = torch.randn((5,5))
a = torch.where(x>0.5, 1.0, 0.0)
# x[indices] = 1
# x[~indices] = 0


#### Torch.where(condtion,input, other)

<b> out = x if condition else y </b>