In [3]:
import torch

# Part 0: The base tensor
# We will use this tensor for all parts of the challenge.
base_tensor = torch.arange(48, dtype=torch.float32).reshape(2, 4, 6)
print("Initial Tensor (base_tensor):")
print(base_tensor)


Initial Tensor (base_tensor):
tensor([[[ 0.,  1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10., 11.],
         [12., 13., 14., 15., 16., 17.],
         [18., 19., 20., 21., 22., 23.]],

        [[24., 25., 26., 27., 28., 29.],
         [30., 31., 32., 33., 34., 35.],
         [36., 37., 38., 39., 40., 41.],
         [42., 43., 44., 45., 46., 47.]]])


Task 1.1: Extract and print a tensor containing the values in the middle two columns of the first "page" (the first 2D slice).

In [6]:
first_page = base_tensor[0]
cols = base_tensor.shape[2]
left = cols//2 - 1
right = ((cols+1)//2) + 1
middle_2_t = first_page[:,left:right]

In [7]:
middle_2_t

tensor([[ 2.,  3.],
        [ 8.,  9.],
        [14., 15.],
        [20., 21.]])

1.2 : Extract and print the last row of the entire tensor. Use negative indexing.
Expected Output: tensor([42., 43., 44., 45., 46., 47.])


In [8]:
last_row = base_tensor[-1,-1,:]

In [9]:
last_row

tensor([42., 43., 44., 45., 46., 47.])

Task 1.3: Extract and print every other column of the second "page" (the second 2D slice).
Expected Output:
tensor([[24., 26., 28.],
        [30., 32., 34.],
        [36., 38., 40.],
        [42., 44., 46.]])

In [29]:
second_page = base_tensor[1,:,:]
every_other = second_page[:,::2]

In [30]:
every_other

tensor([[24., 26., 28.],
        [30., 32., 34.],
        [36., 38., 40.],
        [42., 44., 46.]])

In [31]:
# Part 2: Advanced Indexing with Tensors and Masks
# For this section, we will work with a new index tensor and a boolean mask.
# Setup:
# python
# A new index tensor
indices = torch.tensor([0, 2, 3], dtype=torch.long)

# A new boolean mask tensor
mask = base_tensor[1, :, :] > 35


Task 2.1: Use indices to select and print the first, third, and fourth rows from the second "page" of base_tensor.
Expected Output:
tensor([[24., 25., 26., 27., 28., 29.],
        [36., 37., 38., 39., 40., 41.],
        [42., 43., 44., 45., 46., 47.]])

In [39]:
second_page[indices]

tensor([[24., 25., 26., 27., 28., 29.],
        [36., 37., 38., 39., 40., 41.],
        [42., 43., 44., 45., 46., 47.]])

Task 2.2: Use the boolean mask to select and print only the elements from the second "page" of base_tensor that are greater than 35. The result should be a 1D tensor.
Expected Output:
tensor([36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47.])

In [42]:
second_page[mask]

tensor([36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47.])

Task 2.3: Use the ... (ellipsis) operator to select and print all columns of the third row across all "pages" of the tensor, producing a 2D tensor.
Expected Output:
tensor([[12., 13., 14., 15., 16., 17.],
        [36., 37., 38., 39., 40., 41.]])

In [44]:
base_tensor[:,2,:]

tensor([[12., 13., 14., 15., 16., 17.],
        [36., 37., 38., 39., 40., 41.]])

Part 3: The View vs. Copy Distinction
This is a crucial concept in PyTorch for both memory efficiency and avoiding unexpected side effects.


Task 3.1: View Behavior:
- Use standard slicing to extract the first "page" of base_tensor and assign it to a new variable view_tensor.
- Modify the element at view_tensor[0, 0] to 99.0.
- Print both base_tensor and view_tensor. Explain why base_tensor was also modified.


In [51]:
view_tensor = base_tensor[0]
view_tensor.view(torch.float32)[0,0] = 99.0

In [53]:
print(view_tensor)
print(base_tensor)

tensor([[99.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.],
        [12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.]])
tensor([[[99.,  1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10., 11.],
         [12., 13., 14., 15., 16., 17.],
         [18., 19., 20., 21., 22., 23.]],

        [[24., 25., 26., 27., 28., 29.],
         [30., 31., 32., 33., 34., 35.],
         [36., 37., 38., 39., 40., 41.],
         [42., 43., 44., 45., 46., 47.]]])


Base tensor was also modified because base_tensor[0] is not a seperate object. It points to the same object as base_tensor. And as a result, modifying one tensor will cause the other tensor to change.

This can be prevenetd if a copy is created using .copy() method in torch

In [54]:
copy = torch.view_copy(base_tensor,dtype=torch.float32)

In [56]:
copy[0,0] = 1

In [57]:
print(copy)
print(base_tensor)

tensor([[[ 1.,  1.,  1.,  1.,  1.,  1.],
         [ 6.,  7.,  8.,  9., 10., 11.],
         [12., 13., 14., 15., 16., 17.],
         [18., 19., 20., 21., 22., 23.]],

        [[24., 25., 26., 27., 28., 29.],
         [30., 31., 32., 33., 34., 35.],
         [36., 37., 38., 39., 40., 41.],
         [42., 43., 44., 45., 46., 47.]]])
tensor([[[99.,  1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10., 11.],
         [12., 13., 14., 15., 16., 17.],
         [18., 19., 20., 21., 22., 23.]],

        [[24., 25., 26., 27., 28., 29.],
         [30., 31., 32., 33., 34., 35.],
         [36., 37., 38., 39., 40., 41.],
         [42., 43., 44., 45., 46., 47.]]])


Task 3.2: Copy Behavior
Use advanced indexing (e.g., with an integer list [0, 1]) to extract the first two rows of the first "page" of base_tensor and assign it to a new variable copy_tensor.
Modify the element at copy_tensor[0, 0] to 111.0.
Print both base_tensor and copy_tensor. Explain why base_tensor was not modified this time.

In [ ]:
first_page = base_tensor[0]
copy_tensor = first_page[[0,1]]
copy_tensor[0,0] = 111.0

In [ ]:
first_page = base_tensor[0]
copy_tensor = first_page[[0,1]]
copy_tensor[0,0] = 12.0

In [63]:
print(base_tensor)
print(copy_tensor)

tensor([[[111.,   1.,   2.,   3.,   4.,   5.],
         [  6.,   7.,   8.,   9.,  10.,  11.],
         [ 12.,  13.,  14.,  15.,  16.,  17.],
         [ 18.,  19.,  20.,  21.,  22.,  23.]],

        [[ 24.,  25.,  26.,  27.,  28.,  29.],
         [ 30.,  31.,  32.,  33.,  34.,  35.],
         [ 36.,  37.,  38.,  39.,  40.,  41.],
         [ 42.,  43.,  44.,  45.,  46.,  47.]]])
tensor([[12.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])


Task 4.1: You have a batch of image data represented by base_tensor, where the dimensions are (batch_size, height, width). You need to:
Extract all rows except the first and last row, for both "pages" of the tensor.
Extract every other column from this new slice.
Set all the elements in the resulting tensor to -1.0.
Print the modified base_tensor.
Expected Output (Final base_tensor):



In [74]:
expected_tensor = torch.tensor([[[  0.,   1.,  -1.,   3.,  -1.,   5.],
         [  6.,   7.,  -1.,   9.,  -1.,  11.],
         [ 12.,  13.,  -1.,  15.,  -1.,  17.],
         [ 18.,  19.,  20.,  21.,  22.,  23.]],

        [[ 24.,  25.,  -1.,  27.,  -1.,  29.],
         [ 30.,  31.,  -1.,  33.,  -1.,  35.],
         [ 36.,  37.,  -1.,  39.,  -1.,  41.],
         [ 42.,  43.,  44.,  45.,  46.,  47.]]])

In [85]:
batch = torch.arange(48, dtype=torch.float32).reshape(2, 4, 6)
all_rows = batch[:,0:-1,2::2]
all_rows[:,:,:] = -1

In [86]:
all_rows

tensor([[[-1., -1.],
         [-1., -1.],
         [-1., -1.]],

        [[-1., -1.],
         [-1., -1.],
         [-1., -1.]]])

In [93]:
x,y,z = batch.shape

In [94]:
assert((batch == expected_tensor).sum() == x*y*z)