In [1]:
import torch
import torch.nn as nn

device = "mps" if torch.backends.mps.is_available() else "cpu"

In [13]:
'''
Matrix multiplication and reduction.
Create a random tensor M1 of shape (5, 3) and another random tensor M2 of shape (3, 4).
Perform matrix multiplication using the @ operator.
Then, take the resulting matrix and compute the sum of all its elements.
'''

M = torch.rand((5,3),requires_grad=True).to(device)
N = torch.rand((3,4)).to(device)

P = M @ N
sum = torch.sum(P) # by default, it reduces all the dimensions. Else sums along the specific dimension. 
print(f"Sum of the elements in the tensor : {sum.item()}")

sum.backward()
print(sum.grad)


Sum of the elements in the tensor : 20.046470642089844
None


/var/folders/9b/1tm52gk53x99sw1xshhbwcsc0000gn/T/ipykernel_81720/4144037410.py:16: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:494.)
  print(sum.grad)


In [ ]:

'''
Finding the maximum values and their indices.
Create a tensor with random integer values between 1 and 100, of shape (4, 6). 
Find the maximum value in the entire tensor. 
Then, find the maximum value and its corresponding index for each row.
'''
A = torch.arange(1,100).reshape((4,6)).to(device)
max = torch.max(A).item()
min = torch.min(A).item()

print(f" Max val of tensor : {max} and the min value is : {min}")
max_per_row = torch.tensor(torch.max())


In [9]:

'''
Element-wise exponential and square root.
Create a tensor x using torch.arange from 0 to 9. Compute the element-wise exponential of x (e^x). 
Then, compute the square root of the result.
'''
x = torch.arange(0,9)
ex = torch.exp(x)
sq_ex = torch.sqrt(ex)



In [10]:
print(ex)
print(sq_ex)

tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03])
tensor([ 1.0000,  1.6487,  2.7183,  4.4817,  7.3891, 12.1825, 20.0855, 33.1155,
        54.5981])


In [14]:
'''
Clamping and filtering tensor values.
Create a random tensor of shape (5, 5). Clamp all values in the tensor to be between 0.1 and 0.5.
'''
a = torch.rand((5,5))
clamp_a = torch.clamp(a,min=0.1, max=0.5).to(device) # can store the clamped tensor in another tensor
clamp_b = a.clamp(0.1,0.5) # both are the same way


In [12]:
clamp_a

tensor([[0.5000, 0.2804, 0.2722, 0.5000, 0.3407],
        [0.5000, 0.1494, 0.5000, 0.5000, 0.2805],
        [0.4429, 0.5000, 0.5000, 0.1000, 0.5000],
        [0.5000, 0.5000, 0.1000, 0.5000, 0.1771],
        [0.5000, 0.5000, 0.5000, 0.5000, 0.3814]], device='mps:0')

In [13]:
clamp_b

tensor([[0.5000, 0.2804, 0.2722, 0.5000, 0.3407],
        [0.5000, 0.1494, 0.5000, 0.5000, 0.2805],
        [0.4429, 0.5000, 0.5000, 0.1000, 0.5000],
        [0.5000, 0.5000, 0.1000, 0.5000, 0.1771],
        [0.5000, 0.5000, 0.5000, 0.5000, 0.3814]])